[package]
name = "zb-fwupd"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
semver = { version = "1.0.26", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
