[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
ashv2 = { version = "0.2", git = "https://github.com/PaulmannLighting/ashv2.git" }
clap = { version = "4.5.40", features = ["derive"] }
env_logger = "0.11.8"
ezsp = { version = "0.1", git = "https://github.com/PaulmannLighting/ezsp.git", features = ["ashv2"] }
ezsp-fwupd = { path = "../ezsp_fwupd" }
indicatif = "0.17"
le-stream = { version = "0.5.0", features = ["derive"] }
log = "0.4"
serialport = "4.7"
tokio = { version = "1.44", features = ["macros", "rt", "rt-multi-thread", "sync"] }

[[bin]]
name = "ezsp-fwupd"
path = "src/main.rs"