
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.addr2line]]
version = "0.24.2"
criteria = "safe-to-deploy"

[[exemptions.adler2]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.anstream]]
version = "0.6.19"
criteria = "safe-to-deploy"

[[exemptions.anstyle]]
version = "1.0.11"
criteria = "safe-to-deploy"

[[exemptions.anstyle-parse]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.anstyle-query]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.anstyle-wincon]]
version = "3.0.9"
criteria = "safe-to-deploy"

[[exemptions.ashv2]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.75"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.19.0"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.5.41"
criteria = "safe-to-deploy"

[[exemptions.clap_builder]]
version = "4.5.41"
criteria = "safe-to-deploy"

[[exemptions.clap_derive]]
version = "4.5.41"
criteria = "safe-to-deploy"

[[exemptions.clap_lex]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.colorchoice]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.console]]
version = "0.16.0"
criteria = "safe-to-deploy"

[[exemptions.core-foundation]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.crc]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.crc-catalog]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.encode_unicode]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.enum-iterator]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.enum-iterator-derive]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.env_filter]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.env_logger]]
version = "0.11.8"
criteria = "safe-to-deploy"

[[exemptions.ezsp]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.31.1"
criteria = "safe-to-deploy"

[[exemptions.hash32]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.heapless]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.indicatif]]
version = "0.18.0"
criteria = "safe-to-deploy"

[[exemptions.io-kit-sys]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.io-uring]]
version = "0.7.8"
criteria = "safe-to-deploy"

[[exemptions.is_terminal_polyfill]]
version = "1.70.1"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.jiff]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.jiff-static]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.77"
criteria = "safe-to-deploy"

[[exemptions.le-stream]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.le-stream-derive]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.174"
criteria = "safe-to-deploy"

[[exemptions.libudev]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.libudev-sys]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.27"
criteria = "safe-to-deploy"

[[exemptions.macaddr]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.mach2]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.5"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.8.9"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.nix]]
version = "0.26.4"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.7"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.once_cell_polyfill]]
version = "1.70.1"
criteria = "safe-to-deploy"

[[exemptions.pkg-config]]
version = "0.3.32"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.portable-atomic-util]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.95"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.25"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.20"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.26"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.140"
criteria = "safe-to-deploy"

[[exemptions.serialport]]
version = "4.7.2"
criteria = "safe-to-deploy"

[[exemptions.silizium]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.10"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.104"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.12"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.12"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.46.1"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.unescaper]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.unit-prefix]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.1+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.web-time]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.60.2"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.53.2"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.53.0"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.53.0"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.53.0"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.53.0"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.53.0"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.53.0"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.53.0"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.53.0"
criteria = "safe-to-deploy"
